[package]
name = "simplicate"
version = "0.1.0"
authors = ["don <d.rasiukevicius@labdigital.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.101"
reqwest = "0.9.20"
url = "2.1.0"
